title: eugenio
SEOTitle: Eugenio Sainte Marie | blog
header-img: img/sys/home-bg.jpg
email: e.saintemarie@outlook.com
description: ""
keyword: "Eugenio, Sainte Marie, blog"
url: "https://eugeniosaintemarie.github.io"
baseurl: "/blog"

future: true

RSS: false
twitter_username: ugeniosm
istagram_username: 
linkedin_username:
github_username:

highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json"]
anchorjs: true

plugins: [jekyll-paginate]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

disqus_username:

# Google Analytics
ga_track_id: "" #Format: UA-xxxxxx-xx
ga_domain:

# Sidebar settings
sidebar: true
sidebar-about-description: ""
#sidebar-avatar: sys/img/avatar.jpg

# Tags
featured-tags: true
featured-condition-size: 1

# Friends
#friends: [
#  {
#     title: "",
#     href: ""
#  }
#]

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true
